{{- range .Values.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .name | replace "_" "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ $.Values.project_id }}/secrets/{{ .name }}/versions/latest"
        path: {{ .token }}
---
{{- end }}