{{- range .Values.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .name | replace "_" "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  {{- if eq $.Values.cloudProvider "aws" }}
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .name }}
        objectType: secretsmanager
        objectAlias: {{ .token }}
        region: {{ $.Values.aws.region }}
  secretObjects:
    - secretName: {{ .name | replace "_" "-" }}
      type: Opaque
      data:
        - objectName: {{ .token }}
          key: value
  {{- else if eq $.Values.cloudProvider "gcp" }}
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ $.Values.gcp.project_id }}/secrets/{{ .name }}/versions/latest"
        path: {{ .token }}
  {{- end }}
---
{{- end }}